/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.flume.source.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status { 
  OK, FAILED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"org.apache.flume.source.avro\",\"symbols\":[\"OK\",\"FAILED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
